spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ProjectsResfullSavis
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2008Dialect
      ddl-auto: update
    show-sql: true


